name: Unit Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
          registry-url: "https://npm.pkg.github.com"

      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Dependencies
        run: yarn

      - name: Test
        run: yarn test
